# Generated by Django 5.2 on 2025-04-25 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_photo_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='is_pulic',
        ),
    ]
